In [1]:
import pandas as pd

In [2]:
standings_2015 = pd.read_csv('../data/seasons/2015standings.csv')

In [3]:
standings_2015.columns = [u'Rk', u'Tm', u'Lg', u'G', u'W', u'L', u'W-L%', u'R', u'RA', u'Rdiff',
       u'SOS', u'SRS', u'pythWL', u'Luck', u'Inter', u'Home', u'Road',
       u'ExInn', u'1Run', u'vRHP', u'vLHP', u'vs_over_500', u'vs_under_500']

In [4]:
standings_2015.head()

,Rk,Tm,Lg,G,W,L,W-L%,R,RA,Rdiff,...,Luck,Inter,Home,Road,ExInn,1Run,vRHP,vLHP,vs_over_500,vs_under_500
0,1,STL,NL,162,100,62,0.617,4.0,3.2,0.8,...,4,9-Nov,55-26,45-36,8-Aug,32-23,75-44,25-18,46-31,54-31
1,2,PIT,NL,162,98,64,0.605,4.3,3.7,0.6,...,5,13-7,53-28,45-36,9-Dec,36-17,78-48,20-16,42-32,56-32
2,3,CHC,NL,162,97,65,0.599,4.3,3.8,0.5,...,7,10-Oct,49-32,48-33,13-5,34-21,77-51,20-14,44-32,53-33
3,4,KCR,AL,162,95,67,0.586,4.5,4.0,0.5,...,5,13-7,51-30,44-37,6-Oct,23-17,64-40,31-27,47-43,48-24
4,5,TOR,AL,162,93,69,0.574,5.5,4.1,1.4,...,-9,8-Dec,53-28,40-41,6-Aug,15-28,73-54,20-15,53-33,40-36

In [5]:
standings_2015 = standings_2015.drop(standings_2015.columns[[0, 2, 3, 10, 11, 12, 13, 14, 
                                                             17, 18, 19, 20]], axis=1)

In [6]:
standings_2015.head()

    Tm    W   L   W-L%    R   RA  Rdiff   Home   Road vs_over_500 vs_under_500
0  STL  100  62  0.617  4.0  3.2    0.8  55-26  45-36       46-31        54-31
1  PIT   98  64  0.605  4.3  3.7    0.6  53-28  45-36       42-32        56-32
2  CHC   97  65  0.599  4.3  3.8    0.5  49-32  48-33       44-32        53-33
3  KCR   95  67  0.586  4.5  4.0    0.5  51-30  44-37       47-43        48-24
4  TOR   93  69  0.574  5.5  4.1    1.4  53-28  40-41       53-33        40-36

In [7]:
standings_2015.dtypes

Tm               object
W                 int64
L                 int64
W-L%            float64
R               float64
RA              float64
Rdiff           float64
Home             object
Road             object
vs_over_500      object
vs_under_500     object
dtype: object

In [8]:
standings_2015.rename(columns={'Tm': 'team', 'W': 'wins', 'L': 'losses', 'W-L%': 'win_loss', 'R': 'runs',
                               'RA': 'runs_allowed', 'Rdiff': 'run_differential','Home': 'home_success',
                               'Road': 'road_success'}, inplace=True)

In [9]:
standings_2015.head()

,team,wins,losses,win_loss,runs,runs_allowed,run_differential,home_success,road_success,vs_over_500,vs_under_500
0,STL,100,62,0.617,4.0,3.2,0.8,55-26,45-36,46-31,54-31
1,PIT,98,64,0.605,4.3,3.7,0.6,53-28,45-36,42-32,56-32
2,CHC,97,65,0.599,4.3,3.8,0.5,49-32,48-33,44-32,53-33
3,KCR,95,67,0.586,4.5,4.0,0.5,51-30,44-37,47-43,48-24
4,TOR,93,69,0.574,5.5,4.1,1.4,53-28,40-41,53-33,40-36

In [10]:
standings_2015['home_success'] = standings_2015.home_success.apply(lambda x: int(x.split('-')[0]) - int(x.split('-')[1]))
standings_2015['road_success'] = standings_2015.road_success.apply(lambda x: int(x.split('-')[0]) - int(x.split('-')[1]))
standings_2015['vs_over_500'] = standings_2015.vs_over_500.apply(lambda x: int(x.split('-')[0]) - int(x.split('-')[1]))
standings_2015['vs_under_500'] = standings_2015.vs_under_500.apply(lambda x: int(x.split('-')[0]) - int(x.split('-')[1]))

In [14]:
standings_2015

,team,wins,losses,win_loss,runs,runs_allowed,run_differential,home_success,road_success,vs_over_500,vs_under_500
0,STL,100,62,0.617,4.0,3.2,0.8,29,9,15,23
1,PIT,98,64,0.605,4.3,3.7,0.6,25,9,10,24
2,CHC,97,65,0.599,4.3,3.8,0.5,17,15,12,20
3,KCR,95,67,0.586,4.5,4.0,0.5,21,7,4,24
4,TOR,93,69,0.574,5.5,4.1,1.4,25,-1,20,4
5,LAD,92,70,0.568,4.1,3.7,0.4,29,-7,-9,31
6,NYM,90,72,0.556,4.2,3.8,0.4,17,1,-10,28
7,TEX,88,74,0.543,4.6,4.5,0.1,5,9,12,2
8,NYY,87,75,0.537,4.7,4.3,0.4,9,3,-7,19
9,HOU,86,76,0.531,4.5,3.8,0.7,25,-15,-1,11
10,LAA,85,77,0.525,4.1,4.2,-0.1,17,-9,-10,18
11,SFG,84,78,0.518,4.3,3.9,0.4,13,-7,-4,10
12,WSN,83,79,0.512,4.3,3.9,0.4,11,-7,-9,13
13,MIN,83,79,0.512,4.3,4.3,0.0,11,-7,-4,8
14,CLE,81,80,0.503,4.2,4.0,0.2,-2,3,-5,6
15,BAL,81,81,0.500,4.4,4.3,0.1,16,-16,-14,14
16,TBR,80,82,0.494,4.0,4.0,0.0,0,-2,-12,10
17,ARI,79,83,0.488,4.4,4.4,0.0,-3,-1,-21,17
18,BOS,78,84,0.481,4.6,4.6,0.0,5,-11,-15,9
19,SEA,76,86,0.469,4.0,4.5,-0.4,-9,-1,-14,4
20,CWS,76,86,0.469,3.8,4.3,-0.5,-1,-9,-12,2
21,DET,74,87,0.460,4.3,5.0,-0.7,-5,-8,-8,-5
22,SDP,74,88,0.457,4.0,4.5,-0.5,-3,-11,-17,3
23,MIA,71,91,0.438,3.8,4.2,-0.4,1,-21,-14,-6
24,MIL,68,94,0.420,4.0,4.5,-0.5,-13,-13,-25,-1
25,OAK,68,94,0.420,4.3,4.5,-0.2,-13,-13,-17,-9
26,COL,68,94,0.420,4.5,5.2,-0.7,-9,-17,-24,-2
27,ATL,67,95,0.414,3.5,4.7,-1.2,3,-31,-24,-4
28,CIN,64,98,0.395,4.0,4.7,-0.7,-13,-21,-27,-7
29,PHI,63,99,0.389,3.9,5.0,-1.1,-7,-29,-25,-11

In [16]:
standings_2015.replace('CWS', 'CHW', inplace=True)

In [17]:
teamzipper = dict(zip(['BOS', 'ARI', 'BAL', 'PHI', 'NYM', 'CHC', 'MIN', 'ATL', 'SFG', 'TEX', 'SDP', 'OAK','TBR', 
                'COL', 'WSN','KCR', 'TOR', 'NYY', 'MIA', 'DET', 'STL','PIT', 'CHW', 'MIL', 'CIN', 'HOU', 
                'CLE', 'LAD', 'LAA','SEA'], range(0,31)))

In [18]:
for row in ["team"]:
    standings_2015[row] = standings_2015[row].apply(lambda x: teamzipper[x])

In [19]:
standings_2015.dtypes

team                  int64
wins                  int64
losses                int64
win_loss            float64
runs                float64
runs_allowed        float64
run_differential    float64
home_success          int64
road_success          int64
vs_over_500           int64
vs_under_500          int64
dtype: object

In [20]:
standings_2015.to_csv('standings_2015.csv', sep='\t', encoding='utf-8')