In [1]:
import pandas as pd
import time
from datetime import datetime, timedelta
from datetime import date
import urllib2
from bs4 import BeautifulSoup

In [41]:
#This generates start and end dates for the urls for my data generator
basic_url = 'http://www.baseball-reference.com/games/standings.cgi?year=2015&month='
startyear = ('2015')
startmonth = ('4')
startday = ('5')
endyear = ('2015')
endmonth = ('10')
endday = ('5')

startdate = date(int(startyear), int(startmonth), int(startday))
dates = []
months = []
days = []

while startdate < date(int(endyear), int(endmonth), int(endday)):
    dates.append(startdate)
    months.append(startdate.month)
    days.append(startdate.day)
    startdate += timedelta(days=1)

#this makes a list of urls to iterate over and 
# you may need to rename this function to something meaningful since its main function is to get 
# the dataframes
def data_generator(month, day):
    dfs = []
    for i in range(len(month)):
        url = basic_url+str(month[i])+'&day='+str(day[i])+'&submit=Submit+Date'
        date = "{}-{}-2015".format(month[i], day[i])
        dfs.append(get_day_by_day_results(url, date))
    return dfs

# this function goes to each link, creates a soup, then reads the table structure to pull out the 2 tables
# I need. It creates new rows to which I can append which table it is and the date from the function above
def get_day_by_day_results(url, date):
    soup = BeautifulSoup(urllib2.urlopen(url))
    time.sleep(1)
    t1 = soup.find_all('table', {'class':'padding wide_container'})
    trs = t1[0].find_all('tr')
    second_tr = trs[1]
    second_td = second_tr.find_all('td', {'class':'padding_right'})
    tables = second_td[1].find_all('table')
    al_df = pd.read_html(str(tables[0]))[0] 
    nl_df = pd.read_html(str(tables[1]))[0]
    al_df['type'] = 'al'
    nl_df['type'] = 'nl'
    al_df['date'] = date
    nl_df['date'] = date
    return pd.concat([al_df, nl_df], axis=0)

day_by_day_results = pd.concat(data_generator(months, days), axis=0)

In [44]:
day_by_day_results

     Tm    W   L   W-L%    GB   RS   RA  pythW-L% type       date
0   CLE    0   0  0.000    --    0    0       NaN   al   4-5-2015
1   SEA    0   0  0.000    --    0    0       NaN   al   4-5-2015
2   MIN    0   0  0.000    --    0    0       NaN   al   4-5-2015
3   DET    0   0  0.000    --    0    0       NaN   al   4-5-2015
4   BAL    0   0  0.000    --    0    0       NaN   al   4-5-2015
5   NYY    0   0  0.000    --    0    0       NaN   al   4-5-2015
6   TEX    0   0  0.000    --    0    0       NaN   al   4-5-2015
7   HOU    0   0  0.000    --    0    0       NaN   al   4-5-2015
8   TBR    0   0  0.000    --    0    0       NaN   al   4-5-2015
9   BOS    0   0  0.000    --    0    0       NaN   al   4-5-2015
10  OAK    0   0  0.000    --    0    0       NaN   al   4-5-2015
11  LAA    0   0  0.000    --    0    0       NaN   al   4-5-2015
12  TOR    0   0  0.000    --    0    0       NaN   al   4-5-2015
13  CHW    0   0  0.000    --    0    0       NaN   al   4-5-2015
14  KCR    0   0  0.000    --    0    0       NaN   al   4-5-2015
0   STL    1   0  1.000    --    3    0     1.000   nl   4-5-2015
1   ARI    0   0  0.000   0.5    0    0       NaN   nl   4-5-2015
2   PHI    0   0  0.000   0.5    0    0       NaN   nl   4-5-2015
3   LAD    0   0  0.000   0.5    0    0       NaN   nl   4-5-2015
4   WSN    0   0  0.000   0.5    0    0       NaN   nl   4-5-2015
5   CIN    0   0  0.000   0.5    0    0       NaN   nl   4-5-2015
6   SDP    0   0  0.000   0.5    0    0       NaN   nl   4-5-2015
7   MIL    0   0  0.000   0.5    0    0       NaN   nl   4-5-2015
8   COL    0   0  0.000   0.5    0    0       NaN   nl   4-5-2015
9   SFG    0   0  0.000   0.5    0    0       NaN   nl   4-5-2015
10  ATL    0   0  0.000   0.5    0    0       NaN   nl   4-5-2015
11  NYM    0   0  0.000   0.5    0    0       NaN   nl   4-5-2015
12  PIT    0   0  0.000   0.5    0    0       NaN   nl   4-5-2015
13  MIA    0   0  0.000   0.5    0    0       NaN   nl   4-5-2015
14  CHC    0   1  0.000   1.0    0    3     0.000   nl   4-5-2015
..  ...  ...  ..    ...   ...  ...  ...       ...  ...        ...
0   KCR   95  67  0.586    --  724  641     0.555   al  10-4-2015
1   TOR   93  69  0.574   2.0  891  670     0.628   al  10-4-2015
2   TEX   88  74  0.543   7.0  751  733     0.511   al  10-4-2015
3   NYY   87  75  0.537   8.0  764  698     0.541   al  10-4-2015
4   HOU   86  76  0.531   9.0  729  618     0.575   al  10-4-2015
5   LAA   85  77  0.525  10.0  661  675     0.490   al  10-4-2015
6   MIN   83  79  0.512  12.0  696  700     0.497   al  10-4-2015
7   CLE   81  80  0.503  13.5  669  640     0.520   al  10-4-2015
8   BAL   81  81  0.500  14.0  713  693     0.513   al  10-4-2015
9   TBR   80  82  0.494  15.0  644  642     0.501   al  10-4-2015
10  BOS   78  84  0.481  17.0  748  753     0.497   al  10-4-2015
11  SEA   76  86  0.469  19.0  656  726     0.454   al  10-4-2015
12  CHW   76  86  0.469  19.0  622  701     0.446   al  10-4-2015
13  DET   74  87  0.460  20.5  689  803     0.430   al  10-4-2015
14  OAK   68  94  0.420  27.0  694  729     0.478   al  10-4-2015
0   STL  100  62  0.617    --  647  525     0.594   nl  10-4-2015
1   PIT   98  64  0.605   2.0  697  596     0.571   nl  10-4-2015
2   CHC   97  65  0.599   3.0  689  608     0.557   nl  10-4-2015
3   LAD   92  70  0.568   8.0  667  595     0.552   nl  10-4-2015
4   NYM   90  72  0.556  10.0  683  613     0.549   nl  10-4-2015
5   SFG   84  78  0.519  16.0  696  627     0.548   nl  10-4-2015
6   WSN   83  79  0.512  17.0  703  635     0.546   nl  10-4-2015
7   ARI   79  83  0.488  21.0  720  713     0.504   nl  10-4-2015
8   SDP   74  88  0.457  26.0  650  731     0.446   nl  10-4-2015
9   MIA   71  91  0.438  29.0  613  678     0.454   nl  10-4-2015
10  MIL   68  94  0.420  32.0  655  737     0.446   nl  10-4-2015
11  COL   68  94  0.420  32.0  737  844     0.438   nl  10-4-2015
12  ATL   67  95  0.414  33.0  573  760     0.374   nl  10-4-2015
13  CIN   64  98  0.395  36.0  640  754     0.426   nl  10-4-2015
14  PHI   63  99  0.389  37.0  626  809     0.385   nl  10-4-2015

[5490 rows x 10 columns]

In [45]:
day_by_day_results.to_csv('dailystandings2015.csv', sep='\t', encoding='utf-8')